### ISSUE TITLE
Fastq output

### ISSUE THREAD

**Issue by ColinAnthony** [philliplab/MotifBinner#96]
We spoke at the beginning of having the option to produce fasta or fastq output.
Where the fastq quality would be the average taken from the reads that were used to build the consensus.
This would be a highly useful function since a number of tools only take sam files as input, for which are generated from fastq files

**Comment by philliplab** [comment]
Its in the todo list now

**Comment by philliplab** [comment]
@ColinAnthony I have been thinking about this a lot. It will not be so easy to just take the average since I have to drop the quality data to do some computations. Adding it back in is possible, but it will take a fair bit of development.

At the same time I have been thinking that:
1) The quality information is really poor (look at the article about MiSeq read errors for example)
2) The quality information will change a lot because we are applying the PID method.

Hence I think it will be best to give new qualities to the data based on the number of sequences that was in the bin + the number of mismatches during the consensus construction process.

For example:
A sequence from a bin with 3 reads gets a Z everywhere and in spots where there was a conflict, an O. (quality scores chosen semi-arbitrarily)

In the case of 4 reads then use \ and Q for example.

As a start, I think we can just assign all reads from the consensus process a very high quality say f (which is 38)? Then we can refine it from there.

So I will add an option which says: Add quality? Then you put in the letter you want assigned. Later we can make it use an algorithm (if it will be useful to add mode details to the quality information)

**Comment by ColinAnthony** [comment]
@philliplab mmm, good point. I think assigning high quality to everything for now is a good start. Something like a score of 38 when the base is x>90% of reads, 30 for 90<x>70 and 20 for 70<x>50

**Comment by philliplab** [comment]
It is possible to add this suggestion. I will start planning all the changes that needs to be made.

These functions will have to be modified:
1) process_bin
2) process_file
3) consensus_checker (optionally also check the qualities)
4) mostConsensusString (add the logic here)
5) twoStepConsensusString (make it eat the argument and spit out a warning)
6) construct_consensus (how to handle Biostrings::consensusString? warning?)

These functions are now deprecated, but will need to be modified or deleted:
1) process_all_bins
2) file_to_consensus

**Comment by philliplab** [comment]
The gap removal logic will have to be moved out of process_bin and into the consensus constructor.

**Comment by philliplab** [comment]
moved to bitbucket/trello
